### PR TITLE
Return early when address is falsey

### PR DESCRIPTION
**Pull request by peterjaap**
This fixes a bug when using TIG_PostNL, TIG_PostcodeNL and Amasty_Checkout

### CODE REVIEW

**Comment by tig-jeffreybranderhorst** [comment]
Hi @peterjaap,

Thank you for the pull request. We are going to check out your code chances and add it to the develop version of the RC if it is also still needed there. 
Thank you again for submitting this and thinking along! 

Have a great day,
Jeffrey

**Comment by tig-jeffreybranderhorst** [comment]
Hi @peterjaap,

I asked the team about this, and they checked the new version/RC. In the RC this file does not exist anymore. So I want to thank you for this PR but this won't be added to the new version because the file does not exist anymore.  

Have a great day,
Jeffrey

**Comment by peterjaap** [comment]
@tig-jeffreybranderhorst and this functionality has been removed or refactored? Not just moved to a different file?

**Comment by tig-vincentthart** [comment]
@peterjaap 

thanks again for your input. Recently we released v1.5.1 which should contain the idea behind this PR.
So for now we will close this one.

Have a nice day!

Vincent

**Pull request closed without merging**
